name: ACR Java Build

on:
  workflow_dispatch:

jobs:
  ContainerBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Login to ACR
        uses: docker/login-action@v3.7.0
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ vars.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build \
           -f order-service/Dockerfile \
           -t ${{ secrets.ACR_LOGIN_SERVER }}/order-service:latest \
            order-service
      - name: Push Docker image to acr
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/order-service:latest
